### ISSUE TITLE
Support for Remarkable 2.x

### ISSUE THREAD

**Issue by c00** [jwerre/remarkable_pdfmake#6]
Currently the plugin is tied to version 1.7.x of Remarkable. It would be amazing if 2.x would be supported as well.

**Comment by jwerre** [comment]
I'm not really maintaining this project anymore. You're welcome to create a pull request if you like.

**Comment by c00** [comment]
Alright, good to know. If I have the time, I will. It's definitely a useful plugin for me. For now, let's close the issue then.
